name: CI Development Env
 
on:
  push:
    branches: ["*"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  attire-recommender:
    name: attire-recommender
    uses: ./.github/workflows/runner.yml
    secrets: inherit
    with:
      name: attire-recommender
      run: |
        pnpm run check -F attire-recommender
        pnpm run test -F attire-recommender

  image-transformer:
    name: image-transformer
    uses: ./.github/workflows/runner.yml
    secrets: inherit
    with:
      name: image-transformer
      run: |
        pnpm run check -F image-transformer
        pnpm run test -F image-transformer